version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wellington\wellington

environment:
  nodejs_version: "0.12.2"
  GOPATH: c:\gopath

install:
  # install nodejs and npm
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g grunt-cli
  # install gcc (needed for sqlite3)
  - choco install -y mingw
  - set PATH=C:\tools\mingw64\bin;C:\gopath\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/tools/godep
  - godep restore

build_script:
  #- goxc -tasks='xc archive' -build-ldflags "-X main.version WIN_VER" -bc='windows' -arch='amd64' -pv $(wt_ver) -wd=wt -d=. -n wt
  - go install -ldflags "-X main.version WIN_VER" github.com/wellington/wellington/wt

artifacts:
  - path: C:\gopath\bin\*
    name: wt
